app.common.init();
app.common.initLazyLoad();
// app.common.initAos();
app.common.toggleMobMenu();
app.toggleLanguage.init();
app.headerSearch.init();
app.navigation.init();
app.promoSlider.init();
app.gallerySlider.init();
app.aboutTabs.init();
app.staffSlider.init();
app.toggleHeaderMobBg.init();
