app.common.init();
app.common.initLazyLoad();
app.common.initAos();
app.common.toggleMobMenu();
app.common.showPassword();
app.common.positionSticky();
app.defaultPopup.init();
// app.successPopup.init();
app.toggleLanguage.init();
app.headerSearch.init();
app.navigation.init();
app.promoSlider.init();
app.gallerySlider.init();
app.galleryList.init();
app.galleryLoadMore.init();
// app.toggleGallery.init();
app.aboutTabs.init();
app.catalogSlider.init();
app.tabsSlider.init('.js-gallery-tabs-slider', app.createNewGallery.init);
app.tabsSlider.init('.js-graduates-tabs-slider');
app.staffSlider.init();
app.toggleHeaderMobBg.init();
app.forum.init();
app.map.init();
